//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9157
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.9157.
// 
#pragma warning disable 1591

namespace MobileWhouse.UyumWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UyumWebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WhereClause[]))]
    public partial class UyumWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveUyumObjectFromXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUyumObjectFromXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadUyumObjectCollectionFromXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTableValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataTableWithSQLURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataTableWithSQLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataTableWithPagingSQLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTableValuesWithPermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetObjectToDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetObjectWSDLOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertDataSetToCollectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertDataSetToCollection2OperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDataSetToCollectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertUploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUploadFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UyumWebService() {
            this.Url = "http://localhost:4444/WebService/UyumWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveUyumObjectFromXMLCompletedEventHandler SaveUyumObjectFromXMLCompleted;
        
        /// <remarks/>
        public event DeleteUyumObjectFromXMLCompletedEventHandler DeleteUyumObjectFromXMLCompleted;
        
        /// <remarks/>
        public event LoadUyumObjectCollectionFromXMLCompletedEventHandler LoadUyumObjectCollectionFromXMLCompleted;
        
        /// <remarks/>
        public event GetTableValuesCompletedEventHandler GetTableValuesCompleted;
        
        /// <remarks/>
        public event GetDataTableWithSQLURLCompletedEventHandler GetDataTableWithSQLURLCompleted;
        
        /// <remarks/>
        public event GetDataTableWithSQLCompletedEventHandler GetDataTableWithSQLCompleted;
        
        /// <remarks/>
        public event GetDataTableWithPagingSQLCompletedEventHandler GetDataTableWithPagingSQLCompleted;
        
        /// <remarks/>
        public event GetTableValuesWithPermissionCompletedEventHandler GetTableValuesWithPermissionCompleted;
        
        /// <remarks/>
        public event GetObjectToDataSetCompletedEventHandler GetObjectToDataSetCompleted;
        
        /// <remarks/>
        public event GetObjectWSDLCompletedEventHandler GetObjectWSDLCompleted;
        
        /// <remarks/>
        public event InsertDataSetToCollectionCompletedEventHandler InsertDataSetToCollectionCompleted;
        
        /// <remarks/>
        public event InsertDataSetToCollection2CompletedEventHandler InsertDataSetToCollection2Completed;
        
        /// <remarks/>
        public event UpdateDataSetToCollectionCompletedEventHandler UpdateDataSetToCollectionCompleted;
        
        /// <remarks/>
        public event DeleteObjectCompletedEventHandler DeleteObjectCompleted;
        
        /// <remarks/>
        public event UpdateObjectCompletedEventHandler UpdateObjectCompleted;
        
        /// <remarks/>
        public event UpdateInvoiceCompletedEventHandler UpdateInvoiceCompleted;
        
        /// <remarks/>
        public event InsertUploadFileCompletedEventHandler InsertUploadFileCompleted;
        
        /// <remarks/>
        public event DeleteUploadFileCompletedEventHandler DeleteUploadFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveUyumObjectFromXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfString SaveUyumObjectFromXML(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("SaveUyumObjectFromXML", new object[] {
                        Context});
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        public void SaveUyumObjectFromXMLAsync(UyumServiceRequestOfString Context) {
            this.SaveUyumObjectFromXMLAsync(Context, null);
        }
        
        /// <remarks/>
        public void SaveUyumObjectFromXMLAsync(UyumServiceRequestOfString Context, object userState) {
            if ((this.SaveUyumObjectFromXMLOperationCompleted == null)) {
                this.SaveUyumObjectFromXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveUyumObjectFromXMLOperationCompleted);
            }
            this.InvokeAsync("SaveUyumObjectFromXML", new object[] {
                        Context}, this.SaveUyumObjectFromXMLOperationCompleted, userState);
        }
        
        private void OnSaveUyumObjectFromXMLOperationCompleted(object arg) {
            if ((this.SaveUyumObjectFromXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveUyumObjectFromXMLCompleted(this, new SaveUyumObjectFromXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUyumObjectFromXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfString DeleteUyumObjectFromXML(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("DeleteUyumObjectFromXML", new object[] {
                        Context});
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUyumObjectFromXMLAsync(UyumServiceRequestOfString Context) {
            this.DeleteUyumObjectFromXMLAsync(Context, null);
        }
        
        /// <remarks/>
        public void DeleteUyumObjectFromXMLAsync(UyumServiceRequestOfString Context, object userState) {
            if ((this.DeleteUyumObjectFromXMLOperationCompleted == null)) {
                this.DeleteUyumObjectFromXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUyumObjectFromXMLOperationCompleted);
            }
            this.InvokeAsync("DeleteUyumObjectFromXML", new object[] {
                        Context}, this.DeleteUyumObjectFromXMLOperationCompleted, userState);
        }
        
        private void OnDeleteUyumObjectFromXMLOperationCompleted(object arg) {
            if ((this.DeleteUyumObjectFromXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUyumObjectFromXMLCompleted(this, new DeleteUyumObjectFromXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadUyumObjectCollectionFromXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfString LoadUyumObjectCollectionFromXML(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("LoadUyumObjectCollectionFromXML", new object[] {
                        Context});
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        public void LoadUyumObjectCollectionFromXMLAsync(UyumServiceRequestOfString Context) {
            this.LoadUyumObjectCollectionFromXMLAsync(Context, null);
        }
        
        /// <remarks/>
        public void LoadUyumObjectCollectionFromXMLAsync(UyumServiceRequestOfString Context, object userState) {
            if ((this.LoadUyumObjectCollectionFromXMLOperationCompleted == null)) {
                this.LoadUyumObjectCollectionFromXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadUyumObjectCollectionFromXMLOperationCompleted);
            }
            this.InvokeAsync("LoadUyumObjectCollectionFromXML", new object[] {
                        Context}, this.LoadUyumObjectCollectionFromXMLOperationCompleted, userState);
        }
        
        private void OnLoadUyumObjectCollectionFromXMLOperationCompleted(object arg) {
            if ((this.LoadUyumObjectCollectionFromXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadUyumObjectCollectionFromXMLCompleted(this, new LoadUyumObjectCollectionFromXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTableValues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTableValues(UyumServiceRequestOfTableInfoIn Context) {
            object[] results = this.Invoke("GetTableValues", new object[] {
                        Context});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTableValuesAsync(UyumServiceRequestOfTableInfoIn Context) {
            this.GetTableValuesAsync(Context, null);
        }
        
        /// <remarks/>
        public void GetTableValuesAsync(UyumServiceRequestOfTableInfoIn Context, object userState) {
            if ((this.GetTableValuesOperationCompleted == null)) {
                this.GetTableValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableValuesOperationCompleted);
            }
            this.InvokeAsync("GetTableValues", new object[] {
                        Context}, this.GetTableValuesOperationCompleted, userState);
        }
        
        private void OnGetTableValuesOperationCompleted(object arg) {
            if ((this.GetTableValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTableValuesCompleted(this, new GetTableValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTableWithSQLURL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDataTableWithSQLURL(string userName, string password, string sqlValue) {
            object[] results = this.Invoke("GetDataTableWithSQLURL", new object[] {
                        userName,
                        password,
                        sqlValue});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataTableWithSQLURLAsync(string userName, string password, string sqlValue) {
            this.GetDataTableWithSQLURLAsync(userName, password, sqlValue, null);
        }
        
        /// <remarks/>
        public void GetDataTableWithSQLURLAsync(string userName, string password, string sqlValue, object userState) {
            if ((this.GetDataTableWithSQLURLOperationCompleted == null)) {
                this.GetDataTableWithSQLURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataTableWithSQLURLOperationCompleted);
            }
            this.InvokeAsync("GetDataTableWithSQLURL", new object[] {
                        userName,
                        password,
                        sqlValue}, this.GetDataTableWithSQLURLOperationCompleted, userState);
        }
        
        private void OnGetDataTableWithSQLURLOperationCompleted(object arg) {
            if ((this.GetDataTableWithSQLURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataTableWithSQLURLCompleted(this, new GetDataTableWithSQLURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTableWithSQL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDataTableWithSQL(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("GetDataTableWithSQL", new object[] {
                        Context});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataTableWithSQLAsync(UyumServiceRequestOfString Context) {
            this.GetDataTableWithSQLAsync(Context, null);
        }
        
        /// <remarks/>
        public void GetDataTableWithSQLAsync(UyumServiceRequestOfString Context, object userState) {
            if ((this.GetDataTableWithSQLOperationCompleted == null)) {
                this.GetDataTableWithSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataTableWithSQLOperationCompleted);
            }
            this.InvokeAsync("GetDataTableWithSQL", new object[] {
                        Context}, this.GetDataTableWithSQLOperationCompleted, userState);
        }
        
        private void OnGetDataTableWithSQLOperationCompleted(object arg) {
            if ((this.GetDataTableWithSQLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataTableWithSQLCompleted(this, new GetDataTableWithSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTableWithPagingSQL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfDataTable GetDataTableWithPagingSQL(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("GetDataTableWithPagingSQL", new object[] {
                        Context});
            return ((UyumServiceResponseOfDataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataTableWithPagingSQLAsync(UyumServiceRequestOfString Context) {
            this.GetDataTableWithPagingSQLAsync(Context, null);
        }
        
        /// <remarks/>
        public void GetDataTableWithPagingSQLAsync(UyumServiceRequestOfString Context, object userState) {
            if ((this.GetDataTableWithPagingSQLOperationCompleted == null)) {
                this.GetDataTableWithPagingSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataTableWithPagingSQLOperationCompleted);
            }
            this.InvokeAsync("GetDataTableWithPagingSQL", new object[] {
                        Context}, this.GetDataTableWithPagingSQLOperationCompleted, userState);
        }
        
        private void OnGetDataTableWithPagingSQLOperationCompleted(object arg) {
            if ((this.GetDataTableWithPagingSQLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataTableWithPagingSQLCompleted(this, new GetDataTableWithPagingSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTableValuesWithPermission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTableValuesWithPermission(UyumServiceRequestOfTableInfoIn Context) {
            object[] results = this.Invoke("GetTableValuesWithPermission", new object[] {
                        Context});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTableValuesWithPermissionAsync(UyumServiceRequestOfTableInfoIn Context) {
            this.GetTableValuesWithPermissionAsync(Context, null);
        }
        
        /// <remarks/>
        public void GetTableValuesWithPermissionAsync(UyumServiceRequestOfTableInfoIn Context, object userState) {
            if ((this.GetTableValuesWithPermissionOperationCompleted == null)) {
                this.GetTableValuesWithPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableValuesWithPermissionOperationCompleted);
            }
            this.InvokeAsync("GetTableValuesWithPermission", new object[] {
                        Context}, this.GetTableValuesWithPermissionOperationCompleted, userState);
        }
        
        private void OnGetTableValuesWithPermissionOperationCompleted(object arg) {
            if ((this.GetTableValuesWithPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTableValuesWithPermissionCompleted(this, new GetTableValuesWithPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetObjectToDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetObjectToDataSet(UyumServiceRequestOfObjectInfoIn Context) {
            object[] results = this.Invoke("GetObjectToDataSet", new object[] {
                        Context});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetObjectToDataSetAsync(UyumServiceRequestOfObjectInfoIn Context) {
            this.GetObjectToDataSetAsync(Context, null);
        }
        
        /// <remarks/>
        public void GetObjectToDataSetAsync(UyumServiceRequestOfObjectInfoIn Context, object userState) {
            if ((this.GetObjectToDataSetOperationCompleted == null)) {
                this.GetObjectToDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectToDataSetOperationCompleted);
            }
            this.InvokeAsync("GetObjectToDataSet", new object[] {
                        Context}, this.GetObjectToDataSetOperationCompleted, userState);
        }
        
        private void OnGetObjectToDataSetOperationCompleted(object arg) {
            if ((this.GetObjectToDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetObjectToDataSetCompleted(this, new GetObjectToDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetObjectWSDL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetObjectWSDL(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("GetObjectWSDL", new object[] {
                        Context});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetObjectWSDLAsync(UyumServiceRequestOfString Context) {
            this.GetObjectWSDLAsync(Context, null);
        }
        
        /// <remarks/>
        public void GetObjectWSDLAsync(UyumServiceRequestOfString Context, object userState) {
            if ((this.GetObjectWSDLOperationCompleted == null)) {
                this.GetObjectWSDLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectWSDLOperationCompleted);
            }
            this.InvokeAsync("GetObjectWSDL", new object[] {
                        Context}, this.GetObjectWSDLOperationCompleted, userState);
        }
        
        private void OnGetObjectWSDLOperationCompleted(object arg) {
            if ((this.GetObjectWSDLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetObjectWSDLCompleted(this, new GetObjectWSDLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertDataSetToCollection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertDataSetToCollection(UyumServiceRequestOfDataSet Context) {
            object[] results = this.Invoke("InsertDataSetToCollection", new object[] {
                        Context});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertDataSetToCollectionAsync(UyumServiceRequestOfDataSet Context) {
            this.InsertDataSetToCollectionAsync(Context, null);
        }
        
        /// <remarks/>
        public void InsertDataSetToCollectionAsync(UyumServiceRequestOfDataSet Context, object userState) {
            if ((this.InsertDataSetToCollectionOperationCompleted == null)) {
                this.InsertDataSetToCollectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertDataSetToCollectionOperationCompleted);
            }
            this.InvokeAsync("InsertDataSetToCollection", new object[] {
                        Context}, this.InsertDataSetToCollectionOperationCompleted, userState);
        }
        
        private void OnInsertDataSetToCollectionOperationCompleted(object arg) {
            if ((this.InsertDataSetToCollectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertDataSetToCollectionCompleted(this, new InsertDataSetToCollectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertDataSetToCollection2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertDataSetToCollection2(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement) {
            object[] results = this.Invoke("InsertDataSetToCollection2", new object[] {
                        Context,
                        DisableAutoIncrement});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertDataSetToCollection2Async(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement) {
            this.InsertDataSetToCollection2Async(Context, DisableAutoIncrement, null);
        }
        
        /// <remarks/>
        public void InsertDataSetToCollection2Async(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement, object userState) {
            if ((this.InsertDataSetToCollection2OperationCompleted == null)) {
                this.InsertDataSetToCollection2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertDataSetToCollection2OperationCompleted);
            }
            this.InvokeAsync("InsertDataSetToCollection2", new object[] {
                        Context,
                        DisableAutoIncrement}, this.InsertDataSetToCollection2OperationCompleted, userState);
        }
        
        private void OnInsertDataSetToCollection2OperationCompleted(object arg) {
            if ((this.InsertDataSetToCollection2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertDataSetToCollection2Completed(this, new InsertDataSetToCollection2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateDataSetToCollection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateDataSetToCollection(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement) {
            object[] results = this.Invoke("UpdateDataSetToCollection", new object[] {
                        Context,
                        DisableAutoIncrement});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDataSetToCollectionAsync(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement) {
            this.UpdateDataSetToCollectionAsync(Context, DisableAutoIncrement, null);
        }
        
        /// <remarks/>
        public void UpdateDataSetToCollectionAsync(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement, object userState) {
            if ((this.UpdateDataSetToCollectionOperationCompleted == null)) {
                this.UpdateDataSetToCollectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDataSetToCollectionOperationCompleted);
            }
            this.InvokeAsync("UpdateDataSetToCollection", new object[] {
                        Context,
                        DisableAutoIncrement}, this.UpdateDataSetToCollectionOperationCompleted, userState);
        }
        
        private void OnUpdateDataSetToCollectionOperationCompleted(object arg) {
            if ((this.UpdateDataSetToCollectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDataSetToCollectionCompleted(this, new UpdateDataSetToCollectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteObject(UyumServiceRequestOfObjectDeleteIn Context) {
            object[] results = this.Invoke("DeleteObject", new object[] {
                        Context});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteObjectAsync(UyumServiceRequestOfObjectDeleteIn Context) {
            this.DeleteObjectAsync(Context, null);
        }
        
        /// <remarks/>
        public void DeleteObjectAsync(UyumServiceRequestOfObjectDeleteIn Context, object userState) {
            if ((this.DeleteObjectOperationCompleted == null)) {
                this.DeleteObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteObjectOperationCompleted);
            }
            this.InvokeAsync("DeleteObject", new object[] {
                        Context}, this.DeleteObjectOperationCompleted, userState);
        }
        
        private void OnDeleteObjectOperationCompleted(object arg) {
            if ((this.DeleteObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteObjectCompleted(this, new DeleteObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateObject(UyumServiceRequestOfObjectsIn Context) {
            object[] results = this.Invoke("UpdateObject", new object[] {
                        Context});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateObjectAsync(UyumServiceRequestOfObjectsIn Context) {
            this.UpdateObjectAsync(Context, null);
        }
        
        /// <remarks/>
        public void UpdateObjectAsync(UyumServiceRequestOfObjectsIn Context, object userState) {
            if ((this.UpdateObjectOperationCompleted == null)) {
                this.UpdateObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateObjectOperationCompleted);
            }
            this.InvokeAsync("UpdateObject", new object[] {
                        Context}, this.UpdateObjectOperationCompleted, userState);
        }
        
        private void OnUpdateObjectOperationCompleted(object arg) {
            if ((this.UpdateObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateObjectCompleted(this, new UpdateObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateInvoice(UyumServiceRequestOfInt32 Context) {
            object[] results = this.Invoke("UpdateInvoice", new object[] {
                        Context});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateInvoiceAsync(UyumServiceRequestOfInt32 Context) {
            this.UpdateInvoiceAsync(Context, null);
        }
        
        /// <remarks/>
        public void UpdateInvoiceAsync(UyumServiceRequestOfInt32 Context, object userState) {
            if ((this.UpdateInvoiceOperationCompleted == null)) {
                this.UpdateInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInvoiceOperationCompleted);
            }
            this.InvokeAsync("UpdateInvoice", new object[] {
                        Context}, this.UpdateInvoiceOperationCompleted, userState);
        }
        
        private void OnUpdateInvoiceOperationCompleted(object arg) {
            if ((this.UpdateInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateInvoiceCompleted(this, new UpdateInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertUploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfInt32 InsertUploadFile(UyumServiceRequestOfUploadFileIn Context) {
            object[] results = this.Invoke("InsertUploadFile", new object[] {
                        Context});
            return ((UyumServiceResponseOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public void InsertUploadFileAsync(UyumServiceRequestOfUploadFileIn Context) {
            this.InsertUploadFileAsync(Context, null);
        }
        
        /// <remarks/>
        public void InsertUploadFileAsync(UyumServiceRequestOfUploadFileIn Context, object userState) {
            if ((this.InsertUploadFileOperationCompleted == null)) {
                this.InsertUploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUploadFileOperationCompleted);
            }
            this.InvokeAsync("InsertUploadFile", new object[] {
                        Context}, this.InsertUploadFileOperationCompleted, userState);
        }
        
        private void OnInsertUploadFileOperationCompleted(object arg) {
            if ((this.InsertUploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertUploadFileCompleted(this, new InsertUploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfBoolean DeleteUploadFile(UyumServiceRequestOfInt32 Context) {
            object[] results = this.Invoke("DeleteUploadFile", new object[] {
                        Context});
            return ((UyumServiceResponseOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUploadFileAsync(UyumServiceRequestOfInt32 Context) {
            this.DeleteUploadFileAsync(Context, null);
        }
        
        /// <remarks/>
        public void DeleteUploadFileAsync(UyumServiceRequestOfInt32 Context, object userState) {
            if ((this.DeleteUploadFileOperationCompleted == null)) {
                this.DeleteUploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUploadFileOperationCompleted);
            }
            this.InvokeAsync("DeleteUploadFile", new object[] {
                        Context}, this.DeleteUploadFileOperationCompleted, userState);
        }
        
        private void OnDeleteUploadFileOperationCompleted(object arg) {
            if ((this.DeleteUploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUploadFileCompleted(this, new DeleteUploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfString {
        
        private UyumToken tokenField;
        
        private string valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumToken {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceResponseOfBoolean {
        
        private string messageField;
        
        private bool successField;
        
        private bool valueField;
        
        private int idField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceResponseOfInt32 {
        
        private string messageField;
        
        private bool successField;
        
        private int valueField;
        
        private int idField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileIn {
        
        private int relationObjectField;
        
        private int relationIdField;
        
        private string descriptionField;
        
        private string fileNameField;
        
        private DocumentType documentTypeField;
        
        private System.DateTime validityDateField;
        
        /// <remarks/>
        public int RelationObject {
            get {
                return this.relationObjectField;
            }
            set {
                this.relationObjectField = value;
            }
        }
        
        /// <remarks/>
        public int RelationId {
            get {
                return this.relationIdField;
            }
            set {
                this.relationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public DocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidityDate {
            get {
                return this.validityDateField;
            }
            set {
                this.validityDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DocumentType {
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Genel,
        
        /// <remarks/>
        GarantiBelgesi,
        
        /// <remarks/>
        TeknikResim,
        
        /// <remarks/>
        KullanimKlavuzu,
        
        /// <remarks/>
        Şartname,
        
        /// <remarks/>
        Talimat,
        
        /// <remarks/>
        TeknikBilgi,
        
        /// <remarks/>
        Kontrat,
        
        /// <remarks/>
        Teminat,
        
        /// <remarks/>
        YönetimKuruluKararı,
        
        /// <remarks/>
        EkspertizRaporu,
        
        /// <remarks/>
        Fotoğraf,
        
        /// <remarks/>
        TapuSenedi,
        
        /// <remarks/>
        IhaleKomisyonKararı,
        
        /// <remarks/>
        eFatura,
        
        /// <remarks/>
        eIrsaliye,
        
        /// <remarks/>
        IstinafBasvuruDilekcesi,
        
        /// <remarks/>
        BilirkisiEkRaporu,
        
        /// <remarks/>
        IslahDilekcesi,
        
        /// <remarks/>
        KararIlamı,
        
        /// <remarks/>
        IcraEmri,
        
        /// <remarks/>
        EgitimKatılımBelgesi,
        
        /// <remarks/>
        SertifikaTipi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfUploadFileIn {
        
        private UyumToken tokenField;
        
        private UploadFileIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public UploadFileIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfInt32 {
        
        private UyumToken tokenField;
        
        private int valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectsIn {
        
        private string objectCollectionTypeNameField;
        
        private int idField;
        
        /// <remarks/>
        public string ObjectCollectionTypeName {
            get {
                return this.objectCollectionTypeNameField;
            }
            set {
                this.objectCollectionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfObjectsIn {
        
        private UyumToken tokenField;
        
        private ObjectsIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public ObjectsIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectDeleteIn {
        
        private string objectCollectionTypeNameField;
        
        private int idField;
        
        private int promptValueField;
        
        /// <remarks/>
        public string ObjectCollectionTypeName {
            get {
                return this.objectCollectionTypeNameField;
            }
            set {
                this.objectCollectionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int PromptValue {
            get {
                return this.promptValueField;
            }
            set {
                this.promptValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfObjectDeleteIn {
        
        private UyumToken tokenField;
        
        private ObjectDeleteIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public ObjectDeleteIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfDataSet {
        
        private UyumToken tokenField;
        
        private System.Data.DataSet valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WherePropertyClause {
        
        private string propertyNameField;
        
        private object valueField;
        
        /// <remarks/>
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectInfoIn {
        
        private string objectCollectionTypeNameField;
        
        private bool loadDetailField;
        
        private WherePropertyClause[] whereClauseListField;
        
        /// <remarks/>
        public string ObjectCollectionTypeName {
            get {
                return this.objectCollectionTypeNameField;
            }
            set {
                this.objectCollectionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public bool LoadDetail {
            get {
                return this.loadDetailField;
            }
            set {
                this.loadDetailField = value;
            }
        }
        
        /// <remarks/>
        public WherePropertyClause[] WhereClauseList {
            get {
                return this.whereClauseListField;
            }
            set {
                this.whereClauseListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfObjectInfoIn {
        
        private UyumToken tokenField;
        
        private ObjectInfoIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public ObjectInfoIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceResponseOfDataTable {
        
        private string messageField;
        
        private bool successField;
        
        private System.Data.DataTable valueField;
        
        private int idField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WhereClause {
        
        private string fieldNameField;
        
        private object valueField;
        
        private string operatorField;
        
        private DbType dTypeField;
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public DbType DType {
            get {
                return this.dTypeField;
            }
            set {
                this.dTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DbType {
        
        /// <remarks/>
        AnsiString,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Currency,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Guid,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        Object,
        
        /// <remarks/>
        SByte,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Time,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        UInt64,
        
        /// <remarks/>
        VarNumeric,
        
        /// <remarks/>
        AnsiStringFixedLength,
        
        /// <remarks/>
        StringFixedLength,
        
        /// <remarks/>
        Xml,
        
        /// <remarks/>
        DateTime2,
        
        /// <remarks/>
        DateTimeOffset,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TableInfoIn {
        
        private string tableNameField;
        
        private WhereClause[] whereClauseListField;
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public WhereClause[] WhereClauseList {
            get {
                return this.whereClauseListField;
            }
            set {
                this.whereClauseListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfTableInfoIn {
        
        private UyumToken tokenField;
        
        private TableInfoIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public TableInfoIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9157")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceResponseOfString {
        
        private string messageField;
        
        private bool successField;
        
        private string valueField;
        
        private int idField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void SaveUyumObjectFromXMLCompletedEventHandler(object sender, SaveUyumObjectFromXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveUyumObjectFromXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveUyumObjectFromXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UyumServiceResponseOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UyumServiceResponseOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void DeleteUyumObjectFromXMLCompletedEventHandler(object sender, DeleteUyumObjectFromXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUyumObjectFromXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUyumObjectFromXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UyumServiceResponseOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UyumServiceResponseOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void LoadUyumObjectCollectionFromXMLCompletedEventHandler(object sender, LoadUyumObjectCollectionFromXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadUyumObjectCollectionFromXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadUyumObjectCollectionFromXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UyumServiceResponseOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UyumServiceResponseOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void GetTableValuesCompletedEventHandler(object sender, GetTableValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTableValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTableValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void GetDataTableWithSQLURLCompletedEventHandler(object sender, GetDataTableWithSQLURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataTableWithSQLURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataTableWithSQLURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void GetDataTableWithSQLCompletedEventHandler(object sender, GetDataTableWithSQLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataTableWithSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataTableWithSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void GetDataTableWithPagingSQLCompletedEventHandler(object sender, GetDataTableWithPagingSQLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataTableWithPagingSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataTableWithPagingSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UyumServiceResponseOfDataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UyumServiceResponseOfDataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void GetTableValuesWithPermissionCompletedEventHandler(object sender, GetTableValuesWithPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTableValuesWithPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTableValuesWithPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void GetObjectToDataSetCompletedEventHandler(object sender, GetObjectToDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetObjectToDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetObjectToDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void GetObjectWSDLCompletedEventHandler(object sender, GetObjectWSDLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetObjectWSDLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetObjectWSDLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void InsertDataSetToCollectionCompletedEventHandler(object sender, InsertDataSetToCollectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertDataSetToCollectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertDataSetToCollectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void InsertDataSetToCollection2CompletedEventHandler(object sender, InsertDataSetToCollection2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertDataSetToCollection2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertDataSetToCollection2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void UpdateDataSetToCollectionCompletedEventHandler(object sender, UpdateDataSetToCollectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDataSetToCollectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDataSetToCollectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void DeleteObjectCompletedEventHandler(object sender, DeleteObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void UpdateObjectCompletedEventHandler(object sender, UpdateObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void UpdateInvoiceCompletedEventHandler(object sender, UpdateInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void InsertUploadFileCompletedEventHandler(object sender, InsertUploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertUploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertUploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UyumServiceResponseOfInt32 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UyumServiceResponseOfInt32)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    public delegate void DeleteUploadFileCompletedEventHandler(object sender, DeleteUploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9157")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UyumServiceResponseOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UyumServiceResponseOfBoolean)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591