//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2Mobile_c_v4.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Tr_TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Tr_TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("m2Mobile_c_v4.Resources.Languages.Tr_TR", typeof(Tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazgeç.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string Btn_Exit {
            get {
                return ResourceManager.GetString("Btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string Btn_Ok {
            get {
                return ResourceManager.GetString("Btn_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj Çöz.
        /// </summary>
        internal static string Btn_PackRelease {
            get {
                return ResourceManager.GetString("Btn_PackRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj Seç.
        /// </summary>
        internal static string Btn_SelectPackage {
            get {
                return ResourceManager.GetString("Btn_SelectPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string Btn_Settings {
            get {
                return ResourceManager.GetString("Btn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrsaliye Yap.
        /// </summary>
        internal static string Btn_WayBill {
            get {
                return ResourceManager.GetString("Btn_WayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrsaliye Olşutur.
        /// </summary>
        internal static string Btn_WayBillYap {
            get {
                return ResourceManager.GetString("Btn_WayBillYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string Chk_Delete {
            get {
                return ResourceManager.GetString("Chk_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevk Emri Ambalaj İlave.
        /// </summary>
        internal static string Lbl_AdditionPackage {
            get {
                return ResourceManager.GetString("Lbl_AdditionPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlave Ambalaj İşlemi.
        /// </summary>
        internal static string Lbl_AddPackage {
            get {
                return ResourceManager.GetString("Lbl_AddPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        internal static string Lbl_Amount {
            get {
                return ResourceManager.GetString("Lbl_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason Giriş.
        /// </summary>
        internal static string Lbl_ContractIn {
            get {
                return ResourceManager.GetString("Lbl_ContractIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason Çıkış.
        /// </summary>
        internal static string Lbl_ContractOut {
            get {
                return ResourceManager.GetString("Lbl_ContractOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        internal static string Lbl_Date {
            get {
                return ResourceManager.GetString("Lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barkod Yazma Süresi.
        /// </summary>
        internal static string Lbl_Delay {
            get {
                return ResourceManager.GetString("Lbl_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belge No.
        /// </summary>
        internal static string Lbl_DocNo {
            get {
                return ResourceManager.GetString("Lbl_DocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal Kabul İşlemleri.
        /// </summary>
        internal static string Lbl_GoodsAcceptanceHeader {
            get {
                return ResourceManager.GetString("Lbl_GoodsAcceptanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal Hazırlama İşlemleri.
        /// </summary>
        internal static string Lbl_GoodsShippingHeader {
            get {
                return ResourceManager.GetString("Lbl_GoodsShippingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayım Girişi.
        /// </summary>
        internal static string Lbl_InventoryIn {
            get {
                return ResourceManager.GetString("Lbl_InventoryIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string Lbl_Lang {
            get {
                return ResourceManager.GetString("Lbl_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon No.
        /// </summary>
        internal static string Lbl_OperationNum {
            get {
                return ResourceManager.GetString("Lbl_OperationNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Siparişi.
        /// </summary>
        internal static string Lbl_OrderLabel {
            get {
                return ResourceManager.GetString("Lbl_OrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş No.
        /// </summary>
        internal static string Lbl_OrderNumber {
            get {
                return ResourceManager.GetString("Lbl_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj.
        /// </summary>
        internal static string Lbl_Package {
            get {
                return ResourceManager.GetString("Lbl_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj Kodu.
        /// </summary>
        internal static string Lbl_PackageCode {
            get {
                return ResourceManager.GetString("Lbl_PackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj sevk İrsaliye.
        /// </summary>
        internal static string Lbl_PackageShipping {
            get {
                return ResourceManager.GetString("Lbl_PackageShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj Tipi.
        /// </summary>
        internal static string Lbl_PackageType {
            get {
                return ResourceManager.GetString("Lbl_PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj Çöz.
        /// </summary>
        internal static string Lbl_PackRelease {
            get {
                return ResourceManager.GetString("Lbl_PackRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Lbl_PassWord {
            get {
                return ResourceManager.GetString("Lbl_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Kodu.
        /// </summary>
        internal static string Lbl_PersonelCode {
            get {
                return ResourceManager.GetString("Lbl_PersonelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal Haz.Ref.
        /// </summary>
        internal static string Lbl_PrepGoodRef {
            get {
                return ResourceManager.GetString("Lbl_PrepGoodRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Girişi.
        /// </summary>
        internal static string Lbl_Production {
            get {
                return ResourceManager.GetString("Lbl_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Miktarı.
        /// </summary>
        internal static string Lbl_ProductionRate {
            get {
                return ResourceManager.GetString("Lbl_ProductionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal Hazırlama Ambalaj Oluşturma.
        /// </summary>
        internal static string Lbl_PrpGoodsMP {
            get {
                return ResourceManager.GetString("Lbl_PrpGoodsMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raf.
        /// </summary>
        internal static string Lbl_Rack {
            get {
                return ResourceManager.GetString("Lbl_Rack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raf İşlemleri.
        /// </summary>
        internal static string Lbl_RackProcess {
            get {
                return ResourceManager.GetString("Lbl_RackProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Kod.
        /// </summary>
        internal static string Lbl_RunnerCode {
            get {
                return ResourceManager.GetString("Lbl_RunnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj Seçiniz.
        /// </summary>
        internal static string Lbl_SelectPackge {
            get {
                return ResourceManager.GetString("Lbl_SelectPackge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri İşlemleri.
        /// </summary>
        internal static string Lbl_SerialProcess {
            get {
                return ResourceManager.GetString("Lbl_SerialProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevk Emrinden Ambalaj Oluşturma.
        /// </summary>
        internal static string Lbl_ShipPackage {
            get {
                return ResourceManager.GetString("Lbl_ShipPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakliye Kodu.
        /// </summary>
        internal static string Lbl_ShippingCode {
            get {
                return ResourceManager.GetString("Lbl_ShippingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevk Emri.
        /// </summary>
        internal static string Lbl_ShippingOrder {
            get {
                return ResourceManager.GetString("Lbl_ShippingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakilye Şekli.
        /// </summary>
        internal static string Lbl_ShippingType {
            get {
                return ResourceManager.GetString("Lbl_ShippingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Kodu.
        /// </summary>
        internal static string Lbl_StationCode {
            get {
                return ResourceManager.GetString("Lbl_StationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Hareketleri.
        /// </summary>
        internal static string Lbl_StockMovements {
            get {
                return ResourceManager.GetString("Lbl_StockMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emrine Bağlı Malzeme Çıkışı.
        /// </summary>
        internal static string Lbl_StockOutWP {
            get {
                return ResourceManager.GetString("Lbl_StockOutWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket Kodu.
        /// </summary>
        internal static string Lbl_TransCode {
            get {
                return ResourceManager.GetString("Lbl_TransCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        internal static string Lbl_TransDate {
            get {
                return ResourceManager.GetString("Lbl_TransDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Kodu.
        /// </summary>
        internal static string Lbl_UserCode {
            get {
                return ResourceManager.GetString("Lbl_UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depo.
        /// </summary>
        internal static string Lbl_Warehouse {
            get {
                return ResourceManager.GetString("Lbl_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrsaliye Oluşturma.
        /// </summary>
        internal static string Lbl_Waybill {
            get {
                return ResourceManager.GetString("Lbl_Waybill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrsaliye Kodu.
        /// </summary>
        internal static string Lbl_WaybillCode {
            get {
                return ResourceManager.GetString("Lbl_WaybillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrsaliye Tarihi.
        /// </summary>
        internal static string Lbl_WaybillDate {
            get {
                return ResourceManager.GetString("Lbl_WaybillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrsaliye No.
        /// </summary>
        internal static string Lbl_WaybillNumber {
            get {
                return ResourceManager.GetString("Lbl_WaybillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj İrsaliye Yapma.
        /// </summary>
        internal static string Lbl_WaybillPackage {
            get {
                return ResourceManager.GetString("Lbl_WaybillPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri - Sira.
        /// </summary>
        internal static string Lbl_WaybillSerialOrder {
            get {
                return ResourceManager.GetString("Lbl_WaybillSerialOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emri Miktarı.
        /// </summary>
        internal static string Lbl_WoAmount {
            get {
                return ResourceManager.GetString("Lbl_WoAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emri No.
        /// </summary>
        internal static string Lbl_WorderNo {
            get {
                return ResourceManager.GetString("Lbl_WorderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Yeri.
        /// </summary>
        internal static string Lbl_WorkPlace {
            get {
                return ResourceManager.GetString("Lbl_WorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Servis Adresi.
        /// </summary>
        internal static string Lbl_WsAddr {
            get {
                return ResourceManager.GetString("Lbl_WsAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Tarih Giriniz.
        /// </summary>
        internal static string Msg_Date {
            get {
                return ResourceManager.GetString("Msg_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler Silindi.
        /// </summary>
        internal static string Msg_DeleteSucces {
            get {
                return ResourceManager.GetString("Msg_DeleteSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Bilgisi Hatalı.
        /// </summary>
        internal static string Msg_DepthErr {
            get {
                return ResourceManager.GetString("Msg_DepthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Belge Numarası Giriniz.
        /// </summary>
        internal static string Msg_DocNumber {
            get {
                return ResourceManager.GetString("Msg_DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükseklik Bilgisi Hatalı.
        /// </summary>
        internal static string Msg_HeightErr {
            get {
                return ResourceManager.GetString("Msg_HeightErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgisi hatalı.
        /// </summary>
        internal static string Msg_InfoIncorrect {
            get {
                return ResourceManager.GetString("Msg_InfoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum miktar değeri aşıldı.
        /// </summary>
        internal static string Msg_MaxAmount {
            get {
                return ResourceManager.GetString("Msg_MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazla Adet Girildi.
        /// </summary>
        internal static string Msg_MorePieces {
            get {
                return ResourceManager.GetString("Msg_MorePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinecek Kayıt Bulunamadı.
        /// </summary>
        internal static string Msg_NoRecordDelete {
            get {
                return ResourceManager.GetString("Msg_NoRecordDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ambalaj Kodu Giriniz.
        /// </summary>
        internal static string Msg_PackageCode {
            get {
                return ResourceManager.GetString("Msg_PackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ile başlamalıdır.
        /// </summary>
        internal static string Msg_PreCode {
            get {
                return ResourceManager.GetString("Msg_PreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu sayfa için okutma sıralaması tanımlanmamış.
        /// </summary>
        internal static string Msg_ReadSequence {
            get {
                return ResourceManager.GetString("Msg_ReadSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler Kaydedildi.
        /// </summary>
        internal static string Msg_SaveSucces {
            get {
                return ResourceManager.GetString("Msg_SaveSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler Kaydedilemedi.
        /// </summary>
        internal static string Msg_SaveUnSucces {
            get {
                return ResourceManager.GetString("Msg_SaveUnSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Firma Seçiniz.
        /// </summary>
        internal static string Msg_SelectEntity {
            get {
                return ResourceManager.GetString("Msg_SelectEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önce sipariş seçiniz.
        /// </summary>
        internal static string Msg_SelectOrder {
            get {
                return ResourceManager.GetString("Msg_SelectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen ambalaj kodu seçiniz.
        /// </summary>
        internal static string Msg_SelectPackageCode {
            get {
                return ResourceManager.GetString("Msg_SelectPackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ambalaj TipiSeçiniz.
        /// </summary>
        internal static string Msg_SelectPackageType {
            get {
                return ResourceManager.GetString("Msg_SelectPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Sevk Emri Seçiniz.
        /// </summary>
        internal static string Msg_SelectShipping {
            get {
                return ResourceManager.GetString("Msg_SelectShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket Kodu Seçiniz.
        /// </summary>
        internal static string Msg_SelectTras {
            get {
                return ResourceManager.GetString("Msg_SelectTras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emri Seçinizi.
        /// </summary>
        internal static string Msg_SelectWorkOrder {
            get {
                return ResourceManager.GetString("Msg_SelectWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Hedef Depoyu Seçiniz.
        /// </summary>
        internal static string Msg_TargetDepot {
            get {
                return ResourceManager.GetString("Msg_TargetDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Hareket Kodu Seçiniz.
        /// </summary>
        internal static string Msg_TransactionCode {
            get {
                return ResourceManager.GetString("Msg_TransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrsaliye Oluşturuldu.
        /// </summary>
        internal static string Msg_WalbillCreate {
            get {
                return ResourceManager.GetString("Msg_WalbillCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrsaliye Oluşturulamadı.
        /// </summary>
        internal static string Msg_WalbillNotCreate {
            get {
                return ResourceManager.GetString("Msg_WalbillNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebServis Bağlantısı Başarılı.
        /// </summary>
        internal static string Msg_WebServiceAvailable {
            get {
                return ResourceManager.GetString("Msg_WebServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebServis Bağlantısı Sağlanamadı.
        /// </summary>
        internal static string Msg_WebServiceUnAvailable {
            get {
                return ResourceManager.GetString("Msg_WebServiceUnAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağırlık Bilgisi Hatalı.
        /// </summary>
        internal static string Msg_WeightErr {
            get {
                return ResourceManager.GetString("Msg_WeightErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy Bilgisi Hatalı.
        /// </summary>
        internal static string Msg_WidthErr {
            get {
                return ResourceManager.GetString("Msg_WidthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Değer 0 ve Altında Değer Olamaz.
        /// </summary>
        internal static string Msg_WrongValue {
            get {
                return ResourceManager.GetString("Msg_WrongValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Depo.
        /// </summary>
        internal static string SelectedWareHouse {
            get {
                return ResourceManager.GetString("SelectedWareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Okuma Hızı.
        /// </summary>
        internal static string Tx_WriteDelay {
            get {
                return ResourceManager.GetString("Tx_WriteDelay", resourceCulture);
            }
        }
    }
}
