//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6413
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2Mobile_c_v4.Resources.Languages
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uTerminal.Resources.Languages.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Btn_Exit {
            get {
                return ResourceManager.GetString("Btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Waybill.
        /// </summary>
        internal static string Btn_MakeWayBill {
            get {
                return ResourceManager.GetString("Btn_MakeWayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Btn_Ok {
            get {
                return ResourceManager.GetString("Btn_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Package.
        /// </summary>
        internal static string Btn_PackRelease {
            get {
                return ResourceManager.GetString("Btn_PackRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Package.
        /// </summary>
        internal static string Btn_SelectPackage {
            get {
                return ResourceManager.GetString("Btn_SelectPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Btn_Settings {
            get {
                return ResourceManager.GetString("Btn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make waybill.
        /// </summary>
        internal static string Btn_WayBill {
            get {
                return ResourceManager.GetString("Btn_WayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Chk_Delete {
            get {
                return ResourceManager.GetString("Chk_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Addition.
        /// </summary>
        internal static string Lbl_AdditionPackage {
            get {
                return ResourceManager.GetString("Lbl_AdditionPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Packaging.
        /// </summary>
        internal static string Lbl_AddPackage {
            get {
                return ResourceManager.GetString("Lbl_AddPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Lbl_Amount {
            get {
                return ResourceManager.GetString("Lbl_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract In.
        /// </summary>
        internal static string Lbl_ContractIn {
            get {
                return ResourceManager.GetString("Lbl_ContractIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Out.
        /// </summary>
        internal static string Lbl_ContractOut {
            get {
                return ResourceManager.GetString("Lbl_ContractOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Lbl_Date {
            get {
                return ResourceManager.GetString("Lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Scanner Delay.
        /// </summary>
        internal static string Lbl_Delay {
            get {
                return ResourceManager.GetString("Lbl_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Num.
        /// </summary>
        internal static string Lbl_DocNo {
            get {
                return ResourceManager.GetString("Lbl_DocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Acceptance.
        /// </summary>
        internal static string Lbl_GoodsAcceptanceHeader {
            get {
                return ResourceManager.GetString("Lbl_GoodsAcceptanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Shipping Process.
        /// </summary>
        internal static string Lbl_GoodsShippingHeader {
            get {
                return ResourceManager.GetString("Lbl_GoodsShippingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory .
        /// </summary>
        internal static string Lbl_InventoryIn {
            get {
                return ResourceManager.GetString("Lbl_InventoryIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Lbl_Lang {
            get {
                return ResourceManager.GetString("Lbl_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Num..
        /// </summary>
        internal static string Lbl_OperationNum {
            get {
                return ResourceManager.GetString("Lbl_OperationNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        internal static string Lbl_OrderLabel {
            get {
                return ResourceManager.GetString("Lbl_OrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        internal static string Lbl_OrderNumber {
            get {
                return ResourceManager.GetString("Lbl_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj.
        /// </summary>
        internal static string Lbl_Package {
            get {
                return ResourceManager.GetString("Lbl_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging Code.
        /// </summary>
        internal static string Lbl_PackageCode {
            get {
                return ResourceManager.GetString("Lbl_PackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Waybill.
        /// </summary>
        internal static string Lbl_PackageShipping {
            get {
                return ResourceManager.GetString("Lbl_PackageShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Type.
        /// </summary>
        internal static string Lbl_PackageType {
            get {
                return ResourceManager.GetString("Lbl_PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Package.
        /// </summary>
        internal static string Lbl_PackRelease {
            get {
                return ResourceManager.GetString("Lbl_PackRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwrod.
        /// </summary>
        internal static string Lbl_PassWord {
            get {
                return ResourceManager.GetString("Lbl_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Code.
        /// </summary>
        internal static string Lbl_PersonelCode {
            get {
                return ResourceManager.GetString("Lbl_PersonelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep.Goods Ref..
        /// </summary>
        internal static string Lbl_PrepGoodRef {
            get {
                return ResourceManager.GetString("Lbl_PrepGoodRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Input.
        /// </summary>
        internal static string Lbl_Production {
            get {
                return ResourceManager.GetString("Lbl_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Rate.
        /// </summary>
        internal static string Lbl_ProductionRate {
            get {
                return ResourceManager.GetString("Lbl_ProductionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Goods Make Packing.
        /// </summary>
        internal static string Lbl_PrpGoodsMP {
            get {
                return ResourceManager.GetString("Lbl_PrpGoodsMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack.
        /// </summary>
        internal static string Lbl_Rack {
            get {
                return ResourceManager.GetString("Lbl_Rack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack Process.
        /// </summary>
        internal static string Lbl_RackProcess {
            get {
                return ResourceManager.GetString("Lbl_RackProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner Code.
        /// </summary>
        internal static string Lbl_RunnerCode {
            get {
                return ResourceManager.GetString("Lbl_RunnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Package.
        /// </summary>
        internal static string Lbl_SelectPackge {
            get {
                return ResourceManager.GetString("Lbl_SelectPackge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Process.
        /// </summary>
        internal static string Lbl_SerialProcess {
            get {
                return ResourceManager.GetString("Lbl_SerialProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Order Make Packing.
        /// </summary>
        internal static string Lbl_ShipPackage {
            get {
                return ResourceManager.GetString("Lbl_ShipPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shpping Code.
        /// </summary>
        internal static string Lbl_ShippingCode {
            get {
                return ResourceManager.GetString("Lbl_ShippingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Order.
        /// </summary>
        internal static string Lbl_ShippingOrder {
            get {
                return ResourceManager.GetString("Lbl_ShippingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Type.
        /// </summary>
        internal static string Lbl_ShippingType {
            get {
                return ResourceManager.GetString("Lbl_ShippingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Code.
        /// </summary>
        internal static string Lbl_StationCode {
            get {
                return ResourceManager.GetString("Lbl_StationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Movements.
        /// </summary>
        internal static string Lbl_StockMovements {
            get {
                return ResourceManager.GetString("Lbl_StockMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stock-out on the work order.
        /// </summary>
        internal static string Lbl_StockOutWP {
            get {
                return ResourceManager.GetString("Lbl_StockOutWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans.Code.
        /// </summary>
        internal static string Lbl_TransCode {
            get {
                return ResourceManager.GetString("Lbl_TransCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Lbl_TransDate {
            get {
                return ResourceManager.GetString("Lbl_TransDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        internal static string Lbl_UserCode {
            get {
                return ResourceManager.GetString("Lbl_UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WareHouse.
        /// </summary>
        internal static string Lbl_Warehouse {
            get {
                return ResourceManager.GetString("Lbl_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Waybill.
        /// </summary>
        internal static string Lbl_Waybill {
            get {
                return ResourceManager.GetString("Lbl_Waybill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill Code.
        /// </summary>
        internal static string Lbl_WaybillCode {
            get {
                return ResourceManager.GetString("Lbl_WaybillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill Date.
        /// </summary>
        internal static string Lbl_WaybillDate {
            get {
                return ResourceManager.GetString("Lbl_WaybillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill Num.
        /// </summary>
        internal static string Lbl_WaybillNumber {
            get {
                return ResourceManager.GetString("Lbl_WaybillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Waybill.
        /// </summary>
        internal static string Lbl_WaybillPackage {
            get {
                return ResourceManager.GetString("Lbl_WaybillPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial - Order.
        /// </summary>
        internal static string Lbl_WaybillSerialOrder {
            get {
                return ResourceManager.GetString("Lbl_WaybillSerialOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Work Order.
        /// </summary>
        internal static string Lbl_WoAmount {
            get {
                return ResourceManager.GetString("Lbl_WoAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Num..
        /// </summary>
        internal static string Lbl_WorderNo {
            get {
                return ResourceManager.GetString("Lbl_WorderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Place.
        /// </summary>
        internal static string Lbl_WorkPlace {
            get {
                return ResourceManager.GetString("Lbl_WorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service Address.
        /// </summary>
        internal static string Lbl_WsAddr {
            get {
                return ResourceManager.GetString("Lbl_WsAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Date.
        /// </summary>
        internal static string Msg_Date {
            get {
                return ResourceManager.GetString("Msg_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete success.
        /// </summary>
        internal static string Msg_DeleteSucces {
            get {
                return ResourceManager.GetString("Msg_DeleteSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Data Error.
        /// </summary>
        internal static string Msg_DepthErr {
            get {
                return ResourceManager.GetString("Msg_DepthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Document Number.
        /// </summary>
        internal static string Msg_DocNumber {
            get {
                return ResourceManager.GetString("Msg_DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Data Error.
        /// </summary>
        internal static string Msg_HeightErr {
            get {
                return ResourceManager.GetString("Msg_HeightErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information is incorrect.
        /// </summary>
        internal static string Msg_InfoIncorrect {
            get {
                return ResourceManager.GetString("Msg_InfoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exceeded the maximum amount.
        /// </summary>
        internal static string Msg_MaxAmount {
            get {
                return ResourceManager.GetString("Msg_MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered into more pieces.
        /// </summary>
        internal static string Msg_MorePieces {
            get {
                return ResourceManager.GetString("Msg_MorePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to be deleted.
        /// </summary>
        internal static string Msg_NoRecordDelete {
            get {
                return ResourceManager.GetString("Msg_NoRecordDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code packaging.
        /// </summary>
        internal static string Msg_PackageCode {
            get {
                return ResourceManager.GetString("Msg_PackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be begins.
        /// </summary>
        internal static string Msg_PreCode {
            get {
                return ResourceManager.GetString("Msg_PreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading sequence undefined for this page.
        /// </summary>
        internal static string Msg_ReadSequence {
            get {
                return ResourceManager.GetString("Msg_ReadSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save success.
        /// </summary>
        internal static string Msg_SaveSucces {
            get {
                return ResourceManager.GetString("Msg_SaveSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Unsuccess!!!.
        /// </summary>
        internal static string Msg_SaveUnSucces {
            get {
                return ResourceManager.GetString("Msg_SaveUnSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Company First.
        /// </summary>
        internal static string Msg_SelectEntity {
            get {
                return ResourceManager.GetString("Msg_SelectEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select order first.
        /// </summary>
        internal static string Msg_SelectOrder {
            get {
                return ResourceManager.GetString("Msg_SelectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select package code first.
        /// </summary>
        internal static string Msg_SelectPackageCode {
            get {
                return ResourceManager.GetString("Msg_SelectPackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select type of packaging first.
        /// </summary>
        internal static string Msg_SelectPackageType {
            get {
                return ResourceManager.GetString("Msg_SelectPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Shipping Order first.
        /// </summary>
        internal static string Msg_SelectShipping {
            get {
                return ResourceManager.GetString("Msg_SelectShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Trans Code First.
        /// </summary>
        internal static string Msg_SelectTras {
            get {
                return ResourceManager.GetString("Msg_SelectTras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emri Seçinizi.
        /// </summary>
        internal static string Msg_SelectWorkOrder {
            get {
                return ResourceManager.GetString("Msg_SelectWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Targer Depot.
        /// </summary>
        internal static string Msg_TargetDepot {
            get {
                return ResourceManager.GetString("Msg_TargetDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Transaction Code.
        /// </summary>
        internal static string Msg_TransactionCode {
            get {
                return ResourceManager.GetString("Msg_TransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill Created.
        /// </summary>
        internal static string Msg_WalbillCreate {
            get {
                return ResourceManager.GetString("Msg_WalbillCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Create Waybill.
        /// </summary>
        internal static string Msg_WalbillNotCreate {
            get {
                return ResourceManager.GetString("Msg_WalbillNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webservice Connection Established.
        /// </summary>
        internal static string Msg_WebServiceAvailable {
            get {
                return ResourceManager.GetString("Msg_WebServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webservice Connection Has Failed.
        /// </summary>
        internal static string Msg_WebServiceUnAvailable {
            get {
                return ResourceManager.GetString("Msg_WebServiceUnAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Data Error.
        /// </summary>
        internal static string Msg_WeightErr {
            get {
                return ResourceManager.GetString("Msg_WeightErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width Data Error.
        /// </summary>
        internal static string Msg_WidthErr {
            get {
                return ResourceManager.GetString("Msg_WidthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Warehouse.
        /// </summary>
        internal static string SelectedWareHouse {
            get {
                return ResourceManager.GetString("SelectedWareHouse", resourceCulture);
            }
        }
    }
}
