//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9157
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9157.
// 
namespace MobileWhouse.UyumWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UyumWebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WhereClause[]))]
    public partial class UyumWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UyumWebService() {
            this.Url = "http://localhost:4444/WebService/UyumWebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveUyumObjectFromXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfString SaveUyumObjectFromXML(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("SaveUyumObjectFromXML", new object[] {
                        Context});
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveUyumObjectFromXML(UyumServiceRequestOfString Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveUyumObjectFromXML", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public UyumServiceResponseOfString EndSaveUyumObjectFromXML(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUyumObjectFromXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfString DeleteUyumObjectFromXML(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("DeleteUyumObjectFromXML", new object[] {
                        Context});
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteUyumObjectFromXML(UyumServiceRequestOfString Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteUyumObjectFromXML", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public UyumServiceResponseOfString EndDeleteUyumObjectFromXML(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadUyumObjectCollectionFromXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfString LoadUyumObjectCollectionFromXML(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("LoadUyumObjectCollectionFromXML", new object[] {
                        Context});
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadUyumObjectCollectionFromXML(UyumServiceRequestOfString Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadUyumObjectCollectionFromXML", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public UyumServiceResponseOfString EndLoadUyumObjectCollectionFromXML(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UyumServiceResponseOfString)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTableValues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTableValues(UyumServiceRequestOfTableInfoIn Context) {
            object[] results = this.Invoke("GetTableValues", new object[] {
                        Context});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableValues(UyumServiceRequestOfTableInfoIn Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableValues", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetTableValues(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTableWithSQLURL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDataTableWithSQLURL(string userName, string password, string sqlValue) {
            object[] results = this.Invoke("GetDataTableWithSQLURL", new object[] {
                        userName,
                        password,
                        sqlValue});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataTableWithSQLURL(string userName, string password, string sqlValue, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataTableWithSQLURL", new object[] {
                        userName,
                        password,
                        sqlValue}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetDataTableWithSQLURL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTableWithSQL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDataTableWithSQL(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("GetDataTableWithSQL", new object[] {
                        Context});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataTableWithSQL(UyumServiceRequestOfString Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataTableWithSQL", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetDataTableWithSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTableWithPagingSQL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfDataTable GetDataTableWithPagingSQL(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("GetDataTableWithPagingSQL", new object[] {
                        Context});
            return ((UyumServiceResponseOfDataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataTableWithPagingSQL(UyumServiceRequestOfString Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataTableWithPagingSQL", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public UyumServiceResponseOfDataTable EndGetDataTableWithPagingSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UyumServiceResponseOfDataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTableValuesWithPermission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTableValuesWithPermission(UyumServiceRequestOfTableInfoIn Context) {
            object[] results = this.Invoke("GetTableValuesWithPermission", new object[] {
                        Context});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableValuesWithPermission(UyumServiceRequestOfTableInfoIn Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableValuesWithPermission", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetTableValuesWithPermission(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetObjectToDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetObjectToDataSet(UyumServiceRequestOfObjectInfoIn Context) {
            object[] results = this.Invoke("GetObjectToDataSet", new object[] {
                        Context});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetObjectToDataSet(UyumServiceRequestOfObjectInfoIn Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetObjectToDataSet", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetObjectToDataSet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetObjectWSDL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetObjectWSDL(UyumServiceRequestOfString Context) {
            object[] results = this.Invoke("GetObjectWSDL", new object[] {
                        Context});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetObjectWSDL(UyumServiceRequestOfString Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetObjectWSDL", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetObjectWSDL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertDataSetToCollection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertDataSetToCollection(UyumServiceRequestOfDataSet Context) {
            object[] results = this.Invoke("InsertDataSetToCollection", new object[] {
                        Context});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertDataSetToCollection(UyumServiceRequestOfDataSet Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertDataSetToCollection", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndInsertDataSetToCollection(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertDataSetToCollection2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertDataSetToCollection2(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement) {
            object[] results = this.Invoke("InsertDataSetToCollection2", new object[] {
                        Context,
                        DisableAutoIncrement});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertDataSetToCollection2(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertDataSetToCollection2", new object[] {
                        Context,
                        DisableAutoIncrement}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndInsertDataSetToCollection2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateDataSetToCollection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateDataSetToCollection(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement) {
            object[] results = this.Invoke("UpdateDataSetToCollection", new object[] {
                        Context,
                        DisableAutoIncrement});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateDataSetToCollection(UyumServiceRequestOfDataSet Context, bool DisableAutoIncrement, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateDataSetToCollection", new object[] {
                        Context,
                        DisableAutoIncrement}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUpdateDataSetToCollection(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteObject(UyumServiceRequestOfObjectDeleteIn Context) {
            object[] results = this.Invoke("DeleteObject", new object[] {
                        Context});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteObject(UyumServiceRequestOfObjectDeleteIn Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteObject", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDeleteObject(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateObject(UyumServiceRequestOfObjectsIn Context) {
            object[] results = this.Invoke("UpdateObject", new object[] {
                        Context});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateObject(UyumServiceRequestOfObjectsIn Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateObject", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUpdateObject(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateInvoice(UyumServiceRequestOfInt32 Context) {
            object[] results = this.Invoke("UpdateInvoice", new object[] {
                        Context});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateInvoice(UyumServiceRequestOfInt32 Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateInvoice", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUpdateInvoice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertUploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfInt32 InsertUploadFile(UyumServiceRequestOfUploadFileIn Context) {
            object[] results = this.Invoke("InsertUploadFile", new object[] {
                        Context});
            return ((UyumServiceResponseOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertUploadFile(UyumServiceRequestOfUploadFileIn Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertUploadFile", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public UyumServiceResponseOfInt32 EndInsertUploadFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UyumServiceResponseOfInt32)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UyumServiceResponseOfBoolean DeleteUploadFile(UyumServiceRequestOfInt32 Context) {
            object[] results = this.Invoke("DeleteUploadFile", new object[] {
                        Context});
            return ((UyumServiceResponseOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteUploadFile(UyumServiceRequestOfInt32 Context, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteUploadFile", new object[] {
                        Context}, callback, asyncState);
        }
        
        /// <remarks/>
        public UyumServiceResponseOfBoolean EndDeleteUploadFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UyumServiceResponseOfBoolean)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfString {
        
        private UyumToken tokenField;
        
        private string valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumToken {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceResponseOfBoolean {
        
        private string messageField;
        
        private bool successField;
        
        private bool valueField;
        
        private int idField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceResponseOfInt32 {
        
        private string messageField;
        
        private bool successField;
        
        private int valueField;
        
        private int idField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileIn {
        
        private int relationObjectField;
        
        private int relationIdField;
        
        private string descriptionField;
        
        private string fileNameField;
        
        private DocumentType documentTypeField;
        
        private System.DateTime validityDateField;
        
        /// <remarks/>
        public int RelationObject {
            get {
                return this.relationObjectField;
            }
            set {
                this.relationObjectField = value;
            }
        }
        
        /// <remarks/>
        public int RelationId {
            get {
                return this.relationIdField;
            }
            set {
                this.relationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public DocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidityDate {
            get {
                return this.validityDateField;
            }
            set {
                this.validityDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DocumentType {
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Genel,
        
        /// <remarks/>
        GarantiBelgesi,
        
        /// <remarks/>
        TeknikResim,
        
        /// <remarks/>
        KullanimKlavuzu,
        
        /// <remarks/>
        Şartname,
        
        /// <remarks/>
        Talimat,
        
        /// <remarks/>
        TeknikBilgi,
        
        /// <remarks/>
        Kontrat,
        
        /// <remarks/>
        Teminat,
        
        /// <remarks/>
        YönetimKuruluKararı,
        
        /// <remarks/>
        EkspertizRaporu,
        
        /// <remarks/>
        Fotoğraf,
        
        /// <remarks/>
        TapuSenedi,
        
        /// <remarks/>
        IhaleKomisyonKararı,
        
        /// <remarks/>
        eFatura,
        
        /// <remarks/>
        eIrsaliye,
        
        /// <remarks/>
        IstinafBasvuruDilekcesi,
        
        /// <remarks/>
        BilirkisiEkRaporu,
        
        /// <remarks/>
        IslahDilekcesi,
        
        /// <remarks/>
        KararIlamı,
        
        /// <remarks/>
        IcraEmri,
        
        /// <remarks/>
        EgitimKatılımBelgesi,
        
        /// <remarks/>
        SertifikaTipi,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfUploadFileIn {
        
        private UyumToken tokenField;
        
        private UploadFileIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public UploadFileIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfInt32 {
        
        private UyumToken tokenField;
        
        private int valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectsIn {
        
        private string objectCollectionTypeNameField;
        
        private int idField;
        
        /// <remarks/>
        public string ObjectCollectionTypeName {
            get {
                return this.objectCollectionTypeNameField;
            }
            set {
                this.objectCollectionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfObjectsIn {
        
        private UyumToken tokenField;
        
        private ObjectsIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public ObjectsIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectDeleteIn {
        
        private string objectCollectionTypeNameField;
        
        private int idField;
        
        private int promptValueField;
        
        /// <remarks/>
        public string ObjectCollectionTypeName {
            get {
                return this.objectCollectionTypeNameField;
            }
            set {
                this.objectCollectionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int PromptValue {
            get {
                return this.promptValueField;
            }
            set {
                this.promptValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfObjectDeleteIn {
        
        private UyumToken tokenField;
        
        private ObjectDeleteIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public ObjectDeleteIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfDataSet {
        
        private UyumToken tokenField;
        
        private System.Data.DataSet valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WherePropertyClause {
        
        private string propertyNameField;
        
        private object valueField;
        
        /// <remarks/>
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectInfoIn {
        
        private string objectCollectionTypeNameField;
        
        private bool loadDetailField;
        
        private WherePropertyClause[] whereClauseListField;
        
        /// <remarks/>
        public string ObjectCollectionTypeName {
            get {
                return this.objectCollectionTypeNameField;
            }
            set {
                this.objectCollectionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public bool LoadDetail {
            get {
                return this.loadDetailField;
            }
            set {
                this.loadDetailField = value;
            }
        }
        
        /// <remarks/>
        public WherePropertyClause[] WhereClauseList {
            get {
                return this.whereClauseListField;
            }
            set {
                this.whereClauseListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfObjectInfoIn {
        
        private UyumToken tokenField;
        
        private ObjectInfoIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public ObjectInfoIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceResponseOfDataTable {
        
        private string messageField;
        
        private bool successField;
        
        private System.Data.DataTable valueField;
        
        private int idField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WhereClause {
        
        private string fieldNameField;
        
        private object valueField;
        
        private string operatorField;
        
        private DbType dTypeField;
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public DbType DType {
            get {
                return this.dTypeField;
            }
            set {
                this.dTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DbType {
        
        /// <remarks/>
        AnsiString,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Currency,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Guid,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        Object,
        
        /// <remarks/>
        SByte,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Time,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        UInt64,
        
        /// <remarks/>
        VarNumeric,
        
        /// <remarks/>
        AnsiStringFixedLength,
        
        /// <remarks/>
        StringFixedLength,
        
        /// <remarks/>
        Xml,
        
        /// <remarks/>
        DateTime2,
        
        /// <remarks/>
        DateTimeOffset,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TableInfoIn {
        
        private string tableNameField;
        
        private WhereClause[] whereClauseListField;
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public WhereClause[] WhereClauseList {
            get {
                return this.whereClauseListField;
            }
            set {
                this.whereClauseListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceRequestOfTableInfoIn {
        
        private UyumToken tokenField;
        
        private TableInfoIn valueField;
        
        private int topField;
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public UyumToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public TableInfoIn Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyumServiceResponseOfString {
        
        private string messageField;
        
        private bool successField;
        
        private string valueField;
        
        private int idField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
}
