//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8944
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8944.
// 
namespace m2Mobile_c_v4 {
    using System;
    using System.Data;
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("Ds_Isemri_Rafli")]
    public partial class Ds_Isemri_Rafli : global::System.Data.DataSet {
        
        private Dt_Isemri_Rafli_DetayDataTable tableDt_Isemri_Rafli_Detay;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Ds_Isemri_Rafli() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Dt_Isemri_Rafli_DetayDataTable Dt_Isemri_Rafli_Detay {
            get {
                return this.tableDt_Isemri_Rafli_Detay;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            Ds_Isemri_Rafli cln = ((Ds_Isemri_Rafli)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Dt_Isemri_Rafli_Detay"] != null)) {
                    base.Tables.Add(new Dt_Isemri_Rafli_DetayDataTable(ds.Tables["Dt_Isemri_Rafli_Detay"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableDt_Isemri_Rafli_Detay = ((Dt_Isemri_Rafli_DetayDataTable)(base.Tables["Dt_Isemri_Rafli_Detay"]));
            if ((initTable == true)) {
                if ((this.tableDt_Isemri_Rafli_Detay != null)) {
                    this.tableDt_Isemri_Rafli_Detay.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "Ds_Isemri_Rafli";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Ds_Isemri_Rafli.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDt_Isemri_Rafli_Detay = new Dt_Isemri_Rafli_DetayDataTable();
            base.Tables.Add(this.tableDt_Isemri_Rafli_Detay);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeDt_Isemri_Rafli_Detay() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            Ds_Isemri_Rafli ds = new Ds_Isemri_Rafli();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void Dt_Isemri_Rafli_DetayRowChangeEventHandler(object sender, Dt_Isemri_Rafli_DetayRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Dt_Isemri_Rafli_DetayDataTable : global::System.Data.TypedTableBase<Dt_Isemri_Rafli_DetayRow> {
            
            private global::System.Data.DataColumn columnRaf_Kodu;
            
            private global::System.Data.DataColumn columnStok_Kodu;
            
            private global::System.Data.DataColumn columnStok_Adı;
            
            private global::System.Data.DataColumn columnTip;
            
            private global::System.Data.DataColumn columnOk_Miktar;
            
            private global::System.Data.DataColumn columnItemId;
            
            private global::System.Data.DataColumn columnid;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Dt_Isemri_Rafli_DetayDataTable() {
                this.TableName = "Dt_Isemri_Rafli_Detay";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Dt_Isemri_Rafli_DetayDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Raf_KoduColumn {
                get {
                    return this.columnRaf_Kodu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Stok_KoduColumn {
                get {
                    return this.columnStok_Kodu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Stok_AdıColumn {
                get {
                    return this.columnStok_Adı;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TipColumn {
                get {
                    return this.columnTip;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Ok_MiktarColumn {
                get {
                    return this.columnOk_Miktar;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ItemIdColumn {
                get {
                    return this.columnItemId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Dt_Isemri_Rafli_DetayRow this[int index] {
                get {
                    return ((Dt_Isemri_Rafli_DetayRow)(this.Rows[index]));
                }
            }
            
            public event Dt_Isemri_Rafli_DetayRowChangeEventHandler Dt_Isemri_Rafli_DetayRowChanging;
            
            public event Dt_Isemri_Rafli_DetayRowChangeEventHandler Dt_Isemri_Rafli_DetayRowChanged;
            
            public event Dt_Isemri_Rafli_DetayRowChangeEventHandler Dt_Isemri_Rafli_DetayRowDeleting;
            
            public event Dt_Isemri_Rafli_DetayRowChangeEventHandler Dt_Isemri_Rafli_DetayRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddDt_Isemri_Rafli_DetayRow(Dt_Isemri_Rafli_DetayRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Dt_Isemri_Rafli_DetayRow AddDt_Isemri_Rafli_DetayRow(int Raf_Kodu, string Stok_Kodu, string Stok_Adı, string Tip, decimal Ok_Miktar, int ItemId, int id) {
                Dt_Isemri_Rafli_DetayRow rowDt_Isemri_Rafli_DetayRow = ((Dt_Isemri_Rafli_DetayRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Raf_Kodu,
                        Stok_Kodu,
                        Stok_Adı,
                        Tip,
                        Ok_Miktar,
                        ItemId,
                        id};
                rowDt_Isemri_Rafli_DetayRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDt_Isemri_Rafli_DetayRow);
                return rowDt_Isemri_Rafli_DetayRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                Dt_Isemri_Rafli_DetayDataTable cln = ((Dt_Isemri_Rafli_DetayDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new Dt_Isemri_Rafli_DetayDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnRaf_Kodu = base.Columns["Raf_Kodu"];
                this.columnStok_Kodu = base.Columns["Stok_Kodu"];
                this.columnStok_Adı = base.Columns["Stok_Adı"];
                this.columnTip = base.Columns["Tip"];
                this.columnOk_Miktar = base.Columns["Ok_Miktar"];
                this.columnItemId = base.Columns["ItemId"];
                this.columnid = base.Columns["id"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnRaf_Kodu = new global::System.Data.DataColumn("Raf_Kodu", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRaf_Kodu);
                this.columnStok_Kodu = new global::System.Data.DataColumn("Stok_Kodu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStok_Kodu);
                this.columnStok_Adı = new global::System.Data.DataColumn("Stok_Adı", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStok_Adı);
                this.columnTip = new global::System.Data.DataColumn("Tip", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTip);
                this.columnOk_Miktar = new global::System.Data.DataColumn("Ok_Miktar", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOk_Miktar);
                this.columnItemId = new global::System.Data.DataColumn("ItemId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnItemId);
                this.columnid = new global::System.Data.DataColumn("id", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnid);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Dt_Isemri_Rafli_DetayRow NewDt_Isemri_Rafli_DetayRow() {
                return ((Dt_Isemri_Rafli_DetayRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new Dt_Isemri_Rafli_DetayRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(Dt_Isemri_Rafli_DetayRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Dt_Isemri_Rafli_DetayRowChanged != null)) {
                    this.Dt_Isemri_Rafli_DetayRowChanged(this, new Dt_Isemri_Rafli_DetayRowChangeEvent(((Dt_Isemri_Rafli_DetayRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Dt_Isemri_Rafli_DetayRowChanging != null)) {
                    this.Dt_Isemri_Rafli_DetayRowChanging(this, new Dt_Isemri_Rafli_DetayRowChangeEvent(((Dt_Isemri_Rafli_DetayRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Dt_Isemri_Rafli_DetayRowDeleted != null)) {
                    this.Dt_Isemri_Rafli_DetayRowDeleted(this, new Dt_Isemri_Rafli_DetayRowChangeEvent(((Dt_Isemri_Rafli_DetayRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Dt_Isemri_Rafli_DetayRowDeleting != null)) {
                    this.Dt_Isemri_Rafli_DetayRowDeleting(this, new Dt_Isemri_Rafli_DetayRowChangeEvent(((Dt_Isemri_Rafli_DetayRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveDt_Isemri_Rafli_DetayRow(Dt_Isemri_Rafli_DetayRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                Ds_Isemri_Rafli ds = new Ds_Isemri_Rafli();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Dt_Isemri_Rafli_DetayDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class Dt_Isemri_Rafli_DetayRow : global::System.Data.DataRow {
            
            private Dt_Isemri_Rafli_DetayDataTable tableDt_Isemri_Rafli_Detay;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Dt_Isemri_Rafli_DetayRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDt_Isemri_Rafli_Detay = ((Dt_Isemri_Rafli_DetayDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Raf_Kodu {
                get {
                    try {
                        return ((int)(this[this.tableDt_Isemri_Rafli_Detay.Raf_KoduColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Raf_Kodu\' in table \'Dt_Isemri_Rafli_Detay\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDt_Isemri_Rafli_Detay.Raf_KoduColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Stok_Kodu {
                get {
                    try {
                        return ((string)(this[this.tableDt_Isemri_Rafli_Detay.Stok_KoduColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Stok_Kodu\' in table \'Dt_Isemri_Rafli_Detay\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDt_Isemri_Rafli_Detay.Stok_KoduColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Stok_Adı {
                get {
                    try {
                        return ((string)(this[this.tableDt_Isemri_Rafli_Detay.Stok_AdıColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Stok_Adı\' in table \'Dt_Isemri_Rafli_Detay\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDt_Isemri_Rafli_Detay.Stok_AdıColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Tip {
                get {
                    try {
                        return ((string)(this[this.tableDt_Isemri_Rafli_Detay.TipColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Tip\' in table \'Dt_Isemri_Rafli_Detay\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDt_Isemri_Rafli_Detay.TipColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Ok_Miktar {
                get {
                    try {
                        return ((decimal)(this[this.tableDt_Isemri_Rafli_Detay.Ok_MiktarColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ok_Miktar\' in table \'Dt_Isemri_Rafli_Detay\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDt_Isemri_Rafli_Detay.Ok_MiktarColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ItemId {
                get {
                    try {
                        return ((int)(this[this.tableDt_Isemri_Rafli_Detay.ItemIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ItemId\' in table \'Dt_Isemri_Rafli_Detay\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDt_Isemri_Rafli_Detay.ItemIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int id {
                get {
                    try {
                        return ((int)(this[this.tableDt_Isemri_Rafli_Detay.idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'id\' in table \'Dt_Isemri_Rafli_Detay\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDt_Isemri_Rafli_Detay.idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRaf_KoduNull() {
                return this.IsNull(this.tableDt_Isemri_Rafli_Detay.Raf_KoduColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRaf_KoduNull() {
                this[this.tableDt_Isemri_Rafli_Detay.Raf_KoduColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsStok_KoduNull() {
                return this.IsNull(this.tableDt_Isemri_Rafli_Detay.Stok_KoduColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetStok_KoduNull() {
                this[this.tableDt_Isemri_Rafli_Detay.Stok_KoduColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsStok_AdıNull() {
                return this.IsNull(this.tableDt_Isemri_Rafli_Detay.Stok_AdıColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetStok_AdıNull() {
                this[this.tableDt_Isemri_Rafli_Detay.Stok_AdıColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipNull() {
                return this.IsNull(this.tableDt_Isemri_Rafli_Detay.TipColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipNull() {
                this[this.tableDt_Isemri_Rafli_Detay.TipColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOk_MiktarNull() {
                return this.IsNull(this.tableDt_Isemri_Rafli_Detay.Ok_MiktarColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOk_MiktarNull() {
                this[this.tableDt_Isemri_Rafli_Detay.Ok_MiktarColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsItemIdNull() {
                return this.IsNull(this.tableDt_Isemri_Rafli_Detay.ItemIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetItemIdNull() {
                this[this.tableDt_Isemri_Rafli_Detay.ItemIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidNull() {
                return this.IsNull(this.tableDt_Isemri_Rafli_Detay.idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidNull() {
                this[this.tableDt_Isemri_Rafli_Detay.idColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        public class Dt_Isemri_Rafli_DetayRowChangeEvent : global::System.EventArgs {
            
            private Dt_Isemri_Rafli_DetayRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Dt_Isemri_Rafli_DetayRowChangeEvent(Dt_Isemri_Rafli_DetayRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Dt_Isemri_Rafli_DetayRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace Ds_Isemri_RafliUtil {
    using System;
    using System.Data;
    
    
    public partial class DesignerUtil {
        
        public static bool IsDesignTime() {
            // Determine if this instance is running against .NET Framework by using the MSCoreLib PublicKeyToken
            System.Reflection.Assembly mscorlibAssembly = typeof(int).Assembly;
            if ((mscorlibAssembly != null)) {
                if (mscorlibAssembly.FullName.ToUpper().EndsWith("B77A5C561934E089")) {
                    return true;
                }
            }
            return false;
        }
        
        public static bool IsRunTime() {
            // Determine if this instance is running against .NET Compact Framework by using the MSCoreLib PublicKeyToken
            System.Reflection.Assembly mscorlibAssembly = typeof(int).Assembly;
            if ((mscorlibAssembly != null)) {
                if (mscorlibAssembly.FullName.ToUpper().EndsWith("969DB8053D3322AC")) {
                    return true;
                }
            }
            return false;
        }
    }
}
